# Generated by Django 5.0.3 on 2024-04-10 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_created_at_alter_profile_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlike',
            old_name='asnwer',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('user', 'question')},
        ),
    ]
